version: '2'
services:
  portainer:
    image: portainer/portainer
    ports:
      - "12345:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock
volumes:
  portainer_data:

